language: java
jdk:
- oraclejdk8
cache:
  directories:
    - $HOME/.gradle
    - .gradle
sudo: false
install: true

branches:
  except:
    - /\d+\.\d+-v\d+\.\d+\.\d+/

before_install:
  - sed -i 's/git:/https:/g' .git/config
  - chmod +x ./gradlew
  - ./gradlew -v
script:
  - ./gradlew build tagRelease -Pusr=$USER -Ppsw=$PASS -Ptoken=$TOKEN stats

deploy:
  provider: releases
  api_key:
    secure: J6y+dvHcsPyB/8+Guc7XReDF+H0eYhCQmTi2U3hEa9FCw8W3/QQtBKBa+XExvOYg8dxJ+9PFgGpYrSKwcZTdMFnObTf0RIc5RuTG9iBqlGpZK7U4V+Qr1aDdyYkAU0ug8zMwkBCGVzbEQ/ppfhZex8JWz4NV9GA35TF0ZMmIdINfKENhbpgXvZTbLwynMT/XaIIDJNruBHO2Wq6WY2SYRvOCjSlYNJqgE6hRvWoj5OEzqfI5S9i0EZmxWrHVcHhnUP4b7AolxJwkR017YyWHzmkAx1B69q7b1+vt82ADRicIBA26gwyrEm1PMsewKa1nTRAFeJf8xJ3Zq5BpGg5wOPdjY0ovi5dESgUuUmh/iaom+kEfunF5A2qOQfk4xgACqjI9hVVAIn7dcc2i/wWsgldresdJKpR6Tr0bOsnsIVek3AC6ZApKFrYr9fI6S/OMm5+b59nZWzi3iYFBENDFUxzBoWYGDR+7k9Pp/Q5PJfRSOqmQRH/tZpBNtW2tr0N2WCVmCcEj56huzzHQDAdfkiCvUJzbhb8O5t43pRHN2GrY752d14v6quib8njYbP03j1DR/YnwtE2lMWcU1kX+JXNdWiYDs0+K9kHEUWzNyHBt6udFy55cQAyWRDNT0rPUwLGte9unhRnTPsg1s6UHjIJEvS84ErgU6T0LhTPjjOY=
  file_glob: true
  file: 
    - ./build/libs/*.jar
    - CHANGES.md
  skip_cleanup: true
  on:
    repo: disconsented/Cristallum
    all_branches: true
    
notifications:
 irc:
  channels:
   - "irc.esper.net#Disconsented "
  use_notice: true
  skip_join: true
  template:
   - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
   - "Change view : %{compare_url}"
   - "Build details : %{build_url}"